package review.exceptionhandling;

public class LearnExceptionHandeling {
//five key word : try, catch,throw,throws, finally
    //ArthmeticException
    //it is thrown when excptional condition has occured is an arithmetic operation
    //ArraIndexOutOfBoundsException
    // it is thrown to indicate that an array has been accesses with an illegal index. the index is either negative or greater classNotFoundException
    //This Exception is raised when we try to access a class whose definition is not found
    ///    file NotNOt BoundException
    //     this Exception is raised when a file is not accessible or does not open
    ///   IOE
    /// It is thrown when an input -output operation failed or interrupted
    //      interruptedException
    ///  It is thrown when a thread is waitng, sleeping,or doing some processing, and it is interrupted.
    ///    noSuchFieldException
    //  It is thrown when a class does not contain the fiels (or variable )specified
    //    NoSuchMethodException
    //   It is thrown when accessing a method whic is not found
    //    NullPionterException
    // this exception is raised when reffering to the member of a null object. null resents nothing
    //    numberFormationException
    //   this exception is raised when reffering to the members of a null object. Null represnts nothing
    //  NumberFromexception
    //   This exception is raised when a method could not convert a string into a numeric format
    // RunTimeException

}
